In [2]:
# 1.

import pandas as pd

df = pd.read_csv("Documents/IPL_2023_Batsmen.csv")

print("IPL 2023 Batsmen Dataset:")
print(df.head(10))

IPL 2023 Batsmen Dataset:
        Player Name  Runs  Matches  Average  Strike Rate
0      Shubman Gill   890       17    59.33       157.80
1    Faf du Plessis   730       14    56.15       153.68
2      Devon Conway   672       16    51.69       139.70
3       Virat Kohli   639       14    53.25       139.82
4  Yashasvi Jaiswal   625       14    48.08       163.61
5   Ruturaj Gaikwad   590       16    42.14       147.50
6      David Warner   516       14    36.86       134.10
7       Rinku Singh   474       14    59.25       149.53
8      Ishan Kishan   454       16    30.27       142.77
9  Heinrich Klaasen   448       12    49.77       177.07

In [6]:
# 2.

import pandas as pd

df = pd.read_csv("Documents/IPL_2023_Batsmen.csv")

mean_runs = df["Runs"].mean()
median_runs = df["Runs"].median()
mode_runs = df["Runs"].mode()[0]
minimum_runs = df["Runs"].min()
maximum_runs = df["Runs"].max()

print("Univariate Analysis of Runs")
print("----------------")
print("Mean Runs   :", mean_runs)
print("Median Runs :", median_runs)
print("Mode Runs   :", mode_runs)
print("Minimum Runs:", minimum_runs)
print("Maximum Runs:", maximum_runs)

Univariate Analysis of Runs
----------------
Mean Runs   : 603.8
Median Runs : 607.5
Mode Runs   : 448
Minimum Runs: 448
Maximum Runs: 890

In [7]:
# 3.

import pandas as pd

data = {
    "name": ["Restaurant A", "Restaurant B", "Restaurant C",
             "Restaurant D", "Restaurant E"],
    "rating": [4.5, 4.2, 4.7, 4.0, 4.4],
    "votes": [1200, 850, 1500, 600, 1000],
    "avg_cost": [500, 400, 600, 350, 550]
}
df = pd.DataFrame(data)

print("Top 5 Zomato Restaurants:")
display(df)

correlation = df["rating"].corr(df["votes"])

print("Correlation between Rating and Votes:", correlation)

Top 5 Zomato Restaurants:

           name  rating  votes  avg_cost
0  Restaurant A     4.5   1200       500
1  Restaurant B     4.2    850       400
2  Restaurant C     4.7   1500       600
3  Restaurant D     4.0    600       350
4  Restaurant E     4.4   1000       550

Correlation between Rating and Votes: 0.990071896570823

In [8]:
# 4.

import pandas as pd

df = pd.read_csv("Documents/IPL_2023_Batsmen.csv")

summary = df.describe()

display(summary)

             Runs    Matches    Average  Strike Rate
count   10.000000  10.000000  10.000000    10.000000
mean   603.800000  14.700000  48.679000   150.558000
std    139.697133   1.494434   9.625507    12.955316
min    448.000000  12.000000  30.270000   134.100000
25%    484.500000  14.000000  43.625000   140.557500
50%    607.500000  14.000000  50.730000   148.515000
75%    663.750000  16.000000  55.425000   156.770000
max    890.000000  17.000000  59.330000   177.070000

In [9]:
# 5.

import pandas as pd

df = pd.read_csv("Documents/IPL_2023_Batsmen.csv")

correlation = df["Runs"].corr(df["Matches"])

print("Correlation between Runs and Matches:", correlation)

Correlation between Runs and Matches: 0.5212587088416782